apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: frontend-jeman
  namespace: tap-workload
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: drinks-jeman
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_ssh_secret
    value: jeman-gitlab-credentials
  - name: dockerfile
    value: ./Dockerfile
  source:
    git:
      url: https://gitlab.orangeandbronze.com/jeman.mama/frontend-copy
      ref:
        branch: main
